#cloud-config
autoinstall:
  version: 1

  # adding the default ubuntu-desktop packages to the system.
  packages:
    - ubuntu-desktop
    - filezilla
    - putty
    - openjdk-11-jre
    
  # installing snaps
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    - name: mc-installer
    - name: subiquity
      channel: stable
      classic: true

  # main-User creation

  identity:
    realname: 'Camp Admin'
    username: main
    # A password hash is needed. `mkpasswd --method=SHA-512` can help.
    # mkpasswd can be found in the package 'whois'
    password: '$6$DlXAWRHZXVd7dGOK$VMQBYBKVfDXYHl0pu9gk6/XrrddSKJd66tDXYsajZpgD0Sh1WlAhKHScmDCaIyk/8/NTvm3sIWlVcj.xizT1l0'
    hostname: ubuntu-desktop

  # Tell subiquity not to use LVM, but direct storage layout
  storage:
    layout:
      name: direct

  # set keyboard layout

  keyboard:
    layout: de
    variant: nodeadkeys

  late-commands:
    # get cloudinit
    - curtin in-target -- apt-get install -y cloud-init

    # Download and exec postinstall script
    - wget https://raw.githubusercontent.com/phowobos/Minecraftcamp-Ubuntu-Autoinstall/main/postinstall.sh -P /target/root/
    - curtin in-target --target=/target -- chmod +x /root/postinstall.sh
    - curtin in-target --target=/target -- bash /root/postinstall.sh
    # - rm /target/postinstall.sh
